version: "2.3"
services:
    s_backend:
        build: .
        ipc: host
        container_name: search_backend
        command: "flask run --host=0.0.0.0 --port=5001"
        #volumes:
        #    - .:/develop/
        #command: "tail -F /dev/null"
        environment:
            - DBCONNECT
            - FLASK_APP=app.py
            - FLASK_ENV=development
        ports:
            - 5001:5001
networks:
  default:
    external:
      name: elasticsearch_esnet
