# Default values for ingestion.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ankurgos/proposals
  tag: test
  pullPolicy: Always

replicaCount: 1

mongouser: root
mongopwd: password
mongourl: cosmos-mongodb.default.svc.cluster.local
mongoport: 27017

nameOverride: ""
fullnameOverride: ""


