python -m ingest.scripts.train_postprocess \
    --logdir logs/ --modelcfg /ssd/iain/Cosmos/deployment/configs/model_config.yaml \
    --detect-weights /ssd/iain/Cosmos/deployment/weights/model_weights.pth \
    --device cuda  \
    --train-img-dir       /hdd/iaross/train_dir/images \
    --train-proposals-dir /hdd/iaross/train_dir/proposals \
    --train-xml-dir       /hdd/iaross/train_dir/annotations \
    --val-img-dir       /hdd/iaross/val_dir/images \
    --val-proposals-dir /hdd/iaross/val_dir/proposals \
    --val-xml-dir       /hdd/iaross/val_dir/annotations \
    --num-processes 40 --classcfg /ssd/iain/Cosmos/deployment/configs/model_config.yaml \
    --output-path /ssd/iain/Cosmos/deployment/weights/pp_model_weights.pth
