version: '3.4'

networks:
    swarm_network:
        driver: overlay
        attachable: true

services:
    database:
        image: mariadb
        restart: always
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == cosmos0000.chtc.wisc.edu
        environment:
          - MYSQL_ROOT_PASSWORD
          - MYSQL_USER
          - MYSQL_PASSWORD
        networks:
            swarm_network:

    adminer:
        image: adminer
        restart: always
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == cosmos0000.chtc.wisc.edu
        ports:
            - 8080:8080

        networks:
            swarm_network:
