version: '3'
services:
  visualizer:
    build: visualizer/frontend
    environment:
      # Public URL is settable from the
      # local environment
      - DEBUG=1
      - APPMODE=PREDICTION
      - PUBLIC_URL=./
      - API_BASE_URL=./search
    volumes:
      - visualizer_dist:/user/dist
      - ./visualizer/frontend/src:/user/src
      - ./logs:/logs
    depends_on:
      - search_backend
    networks:
      - cosmosnet

  gateway:
    image: nginx
    ports:
      - "5080:80"
    depends_on:
      - visualizer
    volumes:
      - ./visualizer/frontend/logs:/logs
      - visualizer_dist:/frontend:ro
      - ./visualizer/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cosmosnet

  search_backend:
    build: search_backend
    ipc: host
    container_name: search_backend
    command: "flask run --host=0.0.0.0 --port=5001"
#    depends_on:
#      - es01
#      - es02
    environment:
        - DBCONNECT=mongodb://cosmos:password@mongo-test:27017
        - FLASK_APP=app.py
        - FLASK_ENV=development
#    ports:
#        - 5001:5001
    networks:
      - cosmosnet



volumes:
  visualizer_dist:

networks:
  cosmosnet:
    external:
      name: cosmosnet
