version: '3.4'

networks:
  cosmos_swarm_network:
    external: true

services:
  upload:
    image: ${UPLOAD_IMAGE}
    environment:
      - ELASTIC_ADDRESS
    networks:
      cosmos_swarm_network:
    volumes:
      - ${OUTPUT_DIR}:/output
    command: "python3.8 -m retrieval.scripts.build_elastic_index \
              --host es01 \
              --sections-parquet  /output/documents_5Feb_sections.parquet \
              --documents-parquet /output/documents_5Feb_pdfs.parquet \
              --tables-parquet    /output/documents_5Feb_tables.parquet \
              --figures-parquet   /output/documents_5Feb_figures.parquet \
              --equations-parquet /output/documents_5Feb_equations.parquet"
