FROM continuumio/miniconda3

COPY environment.yml /environment.yml
RUN conda env create -f /environment.yml

RUN echo "source activate $(head -1 /environment.yml | cut -d' ' -f2)" > ~/.bashrc
ENV PATH /opt/conda/envs/$(head -1 /environment.yml | cut -d' ' -f2)/bin:$PATH

COPY weights/ /app
COPY src/ /app
WORKDIR /app
