version: "2.3"
services:
    frontend:
        build: .
        volumes:
            - './cosmos:/app/'
            - '/app/node_modules'
        command: "yarn start"
        ports:
            - 3001:3000



