version: "2.3"
services:
    qa:
        ipc: host
        build: 
            context: .
            dockerfile: Dockerfile
        runtime: nvidia
        volumes:
                  - .:/develop
        command: 
            - /bin/bash
            - -c
            - |
              export LC_ALL=C.UTF-8
              export LANG=C.UTF-8
              flask run --host=0.0.0.0 --port=4000
        environment:
            - SQUAD_DIR=../squad
            - FLASK_APP=app.py
            - FLASK_ENV=development
        ports:
            - 4000:4000


networks:
    default:
        external:
            name: elasticsearch_esnet
