version: '2.3'
services:
    gateway:
      image: uwcosmos/cosmos_viz_gateway
      ports:
        - "5002:80"
      depends_on:
        - image-tagger-api
      volumes:
        - ./_data/logs:/logs
        - ${OUTPUT_DIR}/images:/images:ro
        - ${OUTPUT_DIR}/html/img:/kb-images:ro

    image-tagger-api:
      image: uwcosmos/cosmos_viz_api
      depends_on:
        - db

    db:
      image: uwcosmos/cosmos_viz_db
      environment:
        - POSTGRES_DB=annotations
#      ports:
#        - "54321:5432"
#      expose:
#        - 5432

    import_data:
      image: uwcosmos/cosmos_viz_import_data
      depends_on:
        - db
      environment:
        - PG_CONN_STR=postgresql://postgres:@db:5432/annotations
      volumes:
        - ${OUTPUT_DIR}:/output
        - ${OUTPUT_DIR}/images:/images:rw
 
